language: node_js
sudo: false
node_js:
- 16.2.0
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_2fc69c4133c3_key -iv $encrypted_2fc69c4133c3_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 's-w-k'
- git config --global user.email 's979612095@gmail.com'
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean && hexo g -d
