language: node_js
sudo: false
node_js:
- 8.10.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_859e2228a869_key -iv $encrypted_859e2228a869_iv
  -in travis.enc -out travis -d
- openssl aes-256-cbc -K $encrypted_859e2228a869_key -iv $encrypted_859e2228a869_iv
  -in .travis/travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 's-w-k'
- git config --global user.email 's979612095@gmail.com'
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean && hexo g -d
